config/routes.rb
Rails.application.routes.draw do
  resources :evidences
  resources :alarms
  devise_for :users
  get 'pagelanding/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pagelanding#index'

end

app/models/alarm.rb
class Alarm < ApplicationRecord
  belongs_to :user
  has_many :evidences
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/evidence.rb
class Evidence < ApplicationRecord
  belongs_to :user
  belongs_to :alarm
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :alarms
  has_many :evidences
end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  before_action :set_alarm, only: [:show, :edit, :update, :destroy]

  # GET /alarms
  # GET /alarms.json
  def index
    @alarms = Alarm.all
  end

  # GET /alarms/1
  # GET /alarms/1.json
  def show
  end

  # GET /alarms/new
  def new
    @alarm = Alarm.new
  end

  # GET /alarms/1/edit
  def edit
  end

  # POST /alarms
  # POST /alarms.json
  def create
    @alarm = Alarm.new(alarm_params)

    respond_to do |format|
      if @alarm.save
        format.html { redirect_to @alarm, notice: 'Alarm was successfully created.' }
        format.json { render :show, status: :created, location: @alarm }
      else
        format.html { render :new }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alarms/1
  # PATCH/PUT /alarms/1.json
  def update
    respond_to do |format|
      if @alarm.update(alarm_params)
        format.html { redirect_to @alarm, notice: 'Alarm was successfully updated.' }
        format.json { render :show, status: :ok, location: @alarm }
      else
        format.html { render :edit }
        format.json { render json: @alarm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alarms/1
  # DELETE /alarms/1.json
  def destroy
    @alarm.destroy
    respond_to do |format|
      format.html { redirect_to alarms_url, notice: 'Alarm was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alarm
      @alarm = Alarm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alarm_params
      params.require(:alarm).permit(:user_id, :latitud, :longitud, :descripcion, :tipoAlarma, :estado)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/evidences_controller.rb
class EvidencesController < ApplicationController
  before_action :set_evidence, only: [:show, :edit, :update, :destroy]

  # GET /evidences
  # GET /evidences.json
  def index
    @evidences = Evidence.all
  end

  # GET /evidences/1
  # GET /evidences/1.json
  def show
  end

  # GET /evidences/new
  def new
    @evidence = Evidence.new
  end

  # GET /evidences/1/edit
  def edit
  end

  # POST /evidences
  # POST /evidences.json
  def create
    @evidence = Evidence.new(evidence_params)

    respond_to do |format|
      if @evidence.save
        format.html { redirect_to @evidence, notice: 'Evidence was successfully created.' }
        format.json { render :show, status: :created, location: @evidence }
      else
        format.html { render :new }
        format.json { render json: @evidence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /evidences/1
  # PATCH/PUT /evidences/1.json
  def update
    respond_to do |format|
      if @evidence.update(evidence_params)
        format.html { redirect_to @evidence, notice: 'Evidence was successfully updated.' }
        format.json { render :show, status: :ok, location: @evidence }
      else
        format.html { render :edit }
        format.json { render json: @evidence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /evidences/1
  # DELETE /evidences/1.json
  def destroy
    @evidence.destroy
    respond_to do |format|
      format.html { redirect_to evidences_url, notice: 'Evidence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evidence
      @evidence = Evidence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evidence_params
      params.require(:evidence).permit(:user_id, :alarm_id, :notaEvidencia, :rutaEvidencia)
    end
end

app/controllers/pagelanding_controller.rb
class PagelandingController < ApplicationController
  def index
  end
end

app/helpers/alarms_helper.rb
module AlarmsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/evidences_helper.rb
module EvidencesHelper
end

app/helpers/pagelanding_helper.rb
module PagelandingHelper
end

app/views/alarms/_form.html.erb
<%= form_with(model: alarm, local: true) do |form| %>
  <% if alarm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(alarm.errors.count, "error") %> prohibited this alarm from being saved:</h2>

      <ul>
      <% alarm.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :latitud %>
    <%= form.text_field :latitud %>
  </div>

  <div class="field">
    <%= form.label :longitud %>
    <%= form.text_field :longitud %>
  </div>

  <div class="field">
    <%= form.label :descripcion %>
    <%= form.text_area :descripcion %>
  </div>

  <div class="field">
    <%= form.label :tipoAlarma %>
    <%= form.text_field :tipoAlarma %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/alarms/edit.html.erb
<h1>Editing Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Show', @alarm %> |
<%= link_to 'Back', alarms_path %>

app/views/alarms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alarms</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Latitud</th>
      <th>Longitud</th>
      <th>Descripcion</th>
      <th>Tipoalarma</th>
      <th>Estado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alarms.each do |alarm| %>
      <tr>
        <td><%= alarm.user %></td>
        <td><%= alarm.latitud %></td>
        <td><%= alarm.longitud %></td>
        <td><%= alarm.descripcion %></td>
        <td><%= alarm.tipoAlarma %></td>
        <td><%= alarm.estado %></td>
        <td><%= link_to 'Show', alarm %></td>
        <td><%= link_to 'Edit', edit_alarm_path(alarm) %></td>
        <td><%= link_to 'Destroy', alarm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alarm', new_alarm_path %>

app/views/alarms/new.html.erb
<h1>New Alarm</h1>

<%= render 'form', alarm: @alarm %>

<%= link_to 'Back', alarms_path %>

app/views/alarms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @alarm.user %>
</p>

<p>
  <strong>Latitud:</strong>
  <%= @alarm.latitud %>
</p>

<p>
  <strong>Longitud:</strong>
  <%= @alarm.longitud %>
</p>

<p>
  <strong>Descripcion:</strong>
  <%= @alarm.descripcion %>
</p>

<p>
  <strong>Tipoalarma:</strong>
  <%= @alarm.tipoAlarma %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @alarm.estado %>
</p>

<%= link_to 'Edit', edit_alarm_path(@alarm) %> |
<%= link_to 'Back', alarms_path %>

app/views/evidences/_form.html.erb
<%= form_with(model: evidence, local: true) do |form| %>
  <% if evidence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(evidence.errors.count, "error") %> prohibited this evidence from being saved:</h2>

      <ul>
      <% evidence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :alarm_id %>
    <%= form.text_field :alarm_id %>
  </div>

  <div class="field">
    <%= form.label :notaEvidencia %>
    <%= form.text_area :notaEvidencia %>
  </div>

  <div class="field">
    <%= form.label :rutaEvidencia %>
    <%= form.text_field :rutaEvidencia %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/evidences/edit.html.erb
<h1>Editing Evidence</h1>

<%= render 'form', evidence: @evidence %>

<%= link_to 'Show', @evidence %> |
<%= link_to 'Back', evidences_path %>

app/views/evidences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Evidences</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Alarm</th>
      <th>Notaevidencia</th>
      <th>Rutaevidencia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @evidences.each do |evidence| %>
      <tr>
        <td><%= evidence.user %></td>
        <td><%= evidence.alarm %></td>
        <td><%= evidence.notaEvidencia %></td>
        <td><%= evidence.rutaEvidencia %></td>
        <td><%= link_to 'Show', evidence %></td>
        <td><%= link_to 'Edit', edit_evidence_path(evidence) %></td>
        <td><%= link_to 'Destroy', evidence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evidence', new_evidence_path %>

app/views/evidences/new.html.erb
<h1>New Evidence</h1>

<%= render 'form', evidence: @evidence %>

<%= link_to 'Back', evidences_path %>

app/views/evidences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @evidence.user %>
</p>

<p>
  <strong>Alarm:</strong>
  <%= @evidence.alarm %>
</p>

<p>
  <strong>Notaevidencia:</strong>
  <%= @evidence.notaEvidencia %>
</p>

<p>
  <strong>Rutaevidencia:</strong>
  <%= @evidence.rutaEvidencia %>
</p>

<%= link_to 'Edit', edit_evidence_path(@evidence) %> |
<%= link_to 'Back', evidences_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backendsecuritystreet</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Security Street</title>

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli" rel="stylesheet">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="device-mockups/device-mockups.min.css">

  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pagelanding/index.html.erb
  <div id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="#page-top">Security Street</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#download">Descargar</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#features">Caracteristicas</a>
            </li>
            <li class="nav-item">
              <a class="nav-link js-scroll-trigger" href="#contact">Contacto</a>
            </li>
            <% if user_signed_in? %>
              <li class="nav_item">
                <%= link_to "Cerrar Sesión", destroy_user_session_path, method: :delete, :class => "nav-link js-scroll-trigger" %>
              </li>
            <% else %>
              <li>
                <%= link_to  "Iniciar Sesión", new_user_session_path, :class => "nav-link js-scroll-trigger"%>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <header class="masthead">
      <div class="container h-100">
        <div class="row h-100">
          <div class="col-lg-7 my-auto">
            <div class="header-content mx-auto">
              <h1 class="mb-5">Reporta un incidente o pide ayuda en caso de emergencia, y juntos creamos barrios más seguros</h1>
              <a href="#download" class="btn btn-outline btn-xl js-scroll-trigger">Registrese gratis!</a>
            </div>
          </div>
          <div class="col-lg-5 my-auto">
            <div class="device-container">
              <div class="device-mockup iphone6_plus portrait white">
                <div class="device">
                  <div class="screen">
                    <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                    <img src="img/demo-screen-1.jpg" class="img-fluid" alt="">
                  </div>
                  <div class="button">
                    <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </header>

    <section class="download bg-primary text-center" id="download">
      <div class="container">
        <div class="row">
          <div class="col-md-8 mx-auto">
            <h2 class="section-heading">Informa a tus vecinos</h2>
            <p> si te encuentras en una situación de emergencia o reporta si presencias hechos que comprometen la seguridad de tu algún barrio de la localidad.</p>
            <div class="badges">
              <a class="badge-link" href="#"><img src="img/google-play-badge.svg" alt=""></a>
              <a class="badge-link" href="#"><img src="img/app-store-badge.svg" alt=""></a>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="features" id="features">
      <div class="container">
        <div class="section-heading text-center">
          <h2>Informa a tus vecinos sobre el estado de tu barrio</h2>
          <p class="text-muted">Security Street te permite conocer en tiempo real lo que ocurre en la localidad de Engativa.</p>
          <hr>
        </div>
        <div class="row">
          <div class="col-lg-4 my-auto">
            <div class="device-container">
              <div class="device-mockup iphone6_plus portrait white">
                <div class="device">
                  <div class="screen">
                    <!-- Demo image for screen mockup, you can put an image here, some HTML, an animation, video, or anything else! -->
                    <img src="img/demo-screen-1.jpg" class="img-fluid" alt="">
                  </div>
                  <div class="button">
                    <!-- You can hook the "home button" to some JavaScript events or just remove it -->
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-8 my-auto">
            <div class="container-fluid">
              <div class="row">
                <div class="col-lg-6">
                  <div class="feature-item">
                    <i class="icon-screen-smartphone text-primary"></i>
                    <h3>Descarga la Aplicación</h3>
                    <p class="text-muted">Ready to use HTML/CSS device mockups, no Photoshop required!</p>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="feature-item">
                    <i class="icon-camera text-primary"></i>
                    <h3>Facil de utilizar</h3>
                    <p class="text-muted">Put an image, video, animation, or anything else in the screen!</p>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-lg-6">
                  <div class="feature-item">
                    <i class="icon-present text-primary"></i>
                    <h3>ee to Use</h3>
                    <p class="text-muted">As always, this theme is free to download and use for any purpose!</p>
                  </div>
                </div>
                <div class="col-lg-6">
                  <div class="feature-item">
                    <i class="icon-lock-open text-primary"></i>
                    <h3>Seguridad de Identidad</h3>
                    <p class="text-muted">Since this theme is MIT licensed, you can use it commercially!</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="cta">
      <div class="cta-content">
        <div class="container">
          <h2>Stop waiting.<br>Start building.</h2>
          <a href="#contact" class="btn btn-outline btn-xl js-scroll-trigger">Let's Get Started!</a>
        </div>
      </div>
      <div class="overlay"></div>
    </section>

    <section class="contact bg-primary" id="contact">
      <div class="container">
        <h2>We
          <i class="fa fa-heart"></i>
          new friends!</h2>
        <ul class="list-inline list-social">
          <li class="list-inline-item social-twitter">
            <a href="#">
              <i class="fa fa-twitter"></i>
            </a>
          </li>
          <li class="list-inline-item social-facebook">
            <a href="#">
              <i class="fa fa-facebook"></i>
            </a>
          </li>
          <li class="list-inline-item social-google-plus">
            <a href="#">
              <i class="fa fa-google-plus"></i>
            </a>
          </li>
        </ul>
      </div>
    </section>

    <footer>
      <div class="container">
        <p>&copy; Your Website 2018. All Rights Reserved.</p>
        <ul class="list-inline">
          <li class="list-inline-item">
            <a href="#">Privacy</a>
          </li>
          <li class="list-inline-item">
            <a href="#">Terms</a>
          </li>
          <li class="list-inline-item">
            <a href="#">FAQ</a>
          </li>
        </ul>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for this template - ->
    <script src="js/new-age.min.js"></script>

  </div>